spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: ${MYSQL_PASSWD:passwd}
    hikari:
      minimum-idle: 20
      maximum-pool-size: 200
      connection-timeout: 30000
      max-lifetime: 3000000

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl